[fix] se ajusta yml

diff --git a/.github/workflows/pipeline.yaml b/.github/workflows/pipeline.yaml
--- a/.github/workflows/pipeline.yaml
+++ b/.github/workflows/pipeline.yaml
@@ -14,19 +14,13 @@ jobs:
       - name: Set up Python
         uses: actions/setup-python@v2
         with:
-          python-version: "3.9"
+          python-version: "3.x"
       - name: Install Dependencies
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
       - name: Test
         run: python -m pytest --cov-report=xml --cov=.
-
-      - name: Validate coverage
-        if: steps.calculate_coverage.outputs.coverage_percent < env.MIN_COVERAGE_PERCENT
-        run: |
-          echo "Code coverage is less than the minimum required percentage (${env.MIN_COVERAGE_PERCENT}%), failing the build."
-          exit 1
 
   calculate_coverage:
     needs: build
@@ -46,4 +40,37 @@ jobs:
         coverage_percent=$(( 100 * covered_lines / total_lines ))
         echo "::set-output name=coverage_percent::$coverage_percent%"
 
+  validate_pull_request:
+    needs: [calculate_coverage]
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v2
+      with:
+        ref: ${{ github.event.pull_request.head.sha }}
 
+    - name: Setup Python
+      uses: actions/setup-python@v2
+      with:
+        python-version: '3.x'
+
+    - name: Install dependencies
+      run: |
+        python -m pip install --upgrade pip
+        pip install -r requirements.txt
+
+    - name: Run tests with coverage
+      run: pytest --cov-report=xml --cov=.
+
+    - name: Check coverage percentage
+      run: |
+        total_lines=$(xml sel -t -v "count(//line)" coverage.xml)
+        covered_lines=$(xml sel -t -v "count(//line[@hits!=0])" coverage.xml)
+        coverage_percent=$(( 100 * covered_lines / total_lines ))
+        if [ $coverage_percent -lt ${{ env.MIN_COVERAGE_PERCENT }} ]; then
+          echo "Error: coverage percentage ($coverage_percent%) is below minimum threshold (${MIN_COVERAGE_PERCENT}%)" >&2
+          exit 1
+        fi
+
+env:
+  MIN_COVERAGE_PERCENT: 80
