[fix] se ajusta coverage

diff --git a/.github/workflows/pipeline.yaml b/.github/workflows/pipeline.yaml
--- a/.github/workflows/pipeline.yaml
+++ b/.github/workflows/pipeline.yaml
@@ -18,9 +18,14 @@ jobs:
           pip install -r requirements.txt
       - name: Test
         run: python -m pytest --cov-report=xml --cov=.
-        
+
+      - name: Validate coverage
+        if: steps.calculate_coverage.outputs.coverage_percent < env.MIN_COVERAGE_PERCENT
+        run: |
+          echo "Code coverage is less than the minimum required percentage (${env.MIN_COVERAGE_PERCENT}%), failing the build."
+          exit 1
+
   calculate_coverage:
-    needs: build
     runs-on: ubuntu-latest
     outputs:
       coverage_percent: ${{ steps.calculate_coverage_output.outputs.coverage_percent }}
@@ -31,30 +36,11 @@ jobs:
     - name: Calculate test coverage
       id: calculate_coverage_output
       run: |
-        python -m coverage xml
-        total_lines=$(xml sel -t -v "count(//line)" coverage.xml)
-        covered_lines=$(xml sel -t -v "count(//line[@hits!=0])" coverage.xml)
-        coverage_percent=$(( 100 * covered_lines / total_lines ))
-        echo "::set-output name=coverage_percent::$coverage_percent%"
-
-  validate_pull_request:
-    needs: calculate_coverage
-    runs-on: ubuntu-latest
-    steps:
-    - name: Check code formatting
-      uses: github/codeql-action/codeql-format@v1
-
-    - name: Run tests with coverage
-      run: pytest --cov-report=xml --cov=.
-
-    - name: Check test coverage
-      run: |
         coverage xml
         total_lines=$(xml sel -t -v "count(//line)" coverage.xml)
         covered_lines=$(xml sel -t -v "count(//line[@hits!=0])" coverage.xml)
         coverage_percent=$(( 100 * covered_lines / total_lines ))
-        echo "Coverage: $coverage_percent%"
-        if [[ $coverage_percent -lt ${{ env.MIN_COVERAGE_PERCENT }} ]]; then exit 1; fi
+        echo "::set-output name=coverage_percent::$coverage_percent%"
 
 env:
   MIN_COVERAGE_PERCENT: 50
